mysql:
  hostname: "localhost"
  port: 3306
  username: "root"
  password: "supersecure"
  database: "legendperm"
  max_pool_size: 10
  min_idle_connections: -1 # minus one leads to HikariCP default behaviour
  max_lifetime: 30 # in minutes
